### ISSUE TITLE
trying to replace \u0000 with this transform but doesn't work!

### ISSUE THREAD

**Issue by longxiangzhu** [sysco-middleware/kafka-connect-transform#1]
Hey Man!
      I'm trying to use below config to remove the \u0000 from mysql 8.0 database data, but it looks doest work, can you pls help ? thanks !

      "transforms": "unwrap,dropPrefix,replace000,timestamp",
      "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
      "transforms.unwrap.drop.tombstones": "false",
      "transforms.dropPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
      "transforms.dropPrefix.regex": "fms.fms.(.*)",
      "transforms.dropPrefix.replacement": "$1",
      "transforms.replace000.type": "no.sysco.transform.RegexTransform$Value",
      "transforms.replace000.field": "MEETING_TOPIC",
      "transforms.replace000.field.regex": "\\u0000", 
      "transforms.replace000.field.replacement": "a",
      "transforms.replace000.field.replacement.method": "ALL",

the error msg show as :

 Batch entry 96 INSERT INTO fms_popularize_meeting (rowid,ID,FEE_SEQ,MEETING_DATE,MEETING_START_TIME,MEETING_END_TIME,MEETING_TOPIC,MEETING_DETAIL,PEOPLE_NAME,IS_DELETED,CREATE_BY,
 CREATE_TIME,CREATE_NAME,UPDATE_BY,UPDATE_NAME,UPDATE_TIME,CREATE_ORG_ID,CREATE_ORG_NAME,COMPANY) 
 VALUES (
    '{\"schema\":{\"type\":\"struct\",\"fields\":[{\"type\":\"string\",\"optional\":false,\"field\":\"ID\"}],\"optional\":false,\"name\":\"fms.fms.fms_popularize_meeting.Key\"},
 \"payload\":{\"ID\":\"E183419628\"}}','E183419628','1523534',NULL,'24-JUL-18','24-JUL-18',NULL,'讨论论晚讨论论晚\u0000','全体',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) 
 ON CONFLICT (rowid)  DO UPDATE SET ID=EXCLUDED.ID,FEE_SEQ=EXCLUDED.FEE_SEQ,MEETING_DATE=EXCLUDED.MEETING_DATE,MEETING_START_TIME=EXCLUDED.MEETING_START_TIME,MEETING_END_TIME=EXCLUDED.MEETING_END_TIME,
 MEETING_TOPIC=EXCLUDED.MEETING_TOPIC,MEETING_DETAIL=EXCLUDED.MEETING_DETAIL,PEOPLE_NAME=EXCLUDED.PEOPLE_NAME,IS_DELETED=EXCLUDED.IS_DELETED,CREATE_BY=EXCLUDED.CREATE_BY,
 CREATE_TIME=EXCLUDED.CREATE_TIME,CREATE_NAME=EXCLUDED.CREATE_NAME,UPDATE_BY=EXCLUDED.UPDATE_BY,UPDATE_NAME=EXCLUDED.UPDATE_NAME,UPDATE_TIME=EXCLUDED.UPDATE_TIME,
 CREATE_ORG_ID=EXCLUDED.CREATE_ORG_ID,CREATE_ORG_NAME=EXCLUDED.CREATE_ORG_NAME,COMPANY=EXCLUDED.COMPANY 

 was aborted: ERROR: invalid byte sequence for encoding \"UTF8\": 0x00  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding \"UTF8\": 0x00
org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding \"UTF8\": 0x00
at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:150)
at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:102)
... 11 more
"

**Comment by DineshSanklecha** [comment]
Hi,

were you able to find fix for this issue? I am still facing this issue.
